#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $prefix = "sys_";
    my $name = shift;
    if ($name eq "sbrk") {
	print ".global $prefix$name\n";
	print "$prefix$name:\n";
    } else {
	print ".global $name\n";
	print "$name:\n";
    }
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("pause");
entry("uptime");

entry("trace");     # 用户态下的程序通过调用trace函数来使用跟踪系统调用功能
entry("sysinfo");
entry("kpgtbl");

# 网络相关系统调用
entry("bind");
entry("unbind");
entry("send");
entry("recv");

# lock
entry("rwlktest");
entry("cpupin");

entry("mmap");
entry("munmap");

# 共享内存系统调用
entry("shmget");
entry("shmat");
entry("shmdt");
entry("shmctl");